version: '3.7'

services:
  nginx:
    image: geodjango-nginx:latest
    restart: always
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    volumes:
      - ./public/static:/public/static
    ports:
      - 80:80
    depends_on:
      - app

  app:
    image: geodjango-app:latest
    restart: always
    env_file:
      - .env
    build: 
      context: .
      dockerfile: deploy/python/Dockerfile
    volumes:
      - ./public/static:/public/static
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: kartoza/postgis:14
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
