version: '3.7'

services:
  nginx:
    image: geodjango-nginx:latest
    restart: always
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app

  app:
    image: geodjango-app:latest
    restart: always
    env_file:
      - .env
    build: 
      context: .
      dockerfile: deploy/python/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - migration
      - db

  migration:
    image: geodjango-migration:latest
    restart: "no"
    env_file:
      - .env
    command: sh -c "
      python app/manage.py migrate --no-input
      && python app/manage.py migrate importcities cities
      "
    depends_on:
      - db

  db:
    image: kartoza/postgis:14
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
